# Example secrets file. Copy to secrets.toml and fill in real keys (never commit secrets.toml)

#############################
# AI Configuration
#############################
# OpenAI API key (required for AI assistant). Obtain from:
#   https://platform.openai.com/account/api-keys
# Copy this file to .streamlit/secrets.toml (same folder) and uncomment + fill.
# Never commit secrets.toml.
# OPENAI_API_KEY = "sk-your_openai_key"

# Optional model override (default order tried in code). Examples:
#   gpt-4o-mini, gpt-4o, gpt-4.1, gpt-3.5-turbo
# OPENAI_MODEL = "gpt-4o-mini"

# You can also set these as environment variables instead of secrets file.
