# Example secrets file. Copy to secrets.toml and fill in real keys (never commit secrets.toml)

# OpenAI API key (required for AI assistant)
# OPENAI_API_KEY = "sk-your_openai_key"
# Optional model override (default set in code)
# OPENAI_MODEL = "gpt-4o-mini"
