# Example secrets file. Copy to secrets.toml and fill in real keys (never commit secrets.toml)

# --- Weather / Climate APIs ---
# Primary key for OpenWeather (forecast & pollution)
# OPENWEATHER_API_KEY = "your_openweather_key"

# --- AI Providers (optional) ---
# OPENAI_API_KEY = "sk-your_openai_key"
# Optional model override (default handled in code)
# OPENAI_MODEL = "gpt-4o-mini"

# Gemini (Google) AI key (optional)
# GEMINI_API_KEY = "your_gemini_key"

# Other optional future keys could go here (e.g., MAPBOX_API_KEY)

# NOTE: Do not put quotes around integers or booleans if added later.
