# Local secrets for Streamlit (DO NOT COMMIT REAL KEYS)
# Copy this file to secrets.toml locally and insert your real values.

# OpenAI configuration
OPENAI_API_KEY = "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"
## Optional model override
# OPENAI_MODEL = "gpt-4o-mini"
